version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: opendata
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opendata
